apiVersion: apps/v1
kind: Deployment
metadata:
  # Используем встроенную функцию Helm для генерации уникального имени
  name: {{ include "whoami.fullname" . }}
  labels:
    {{- include "whoami.labels" . | nindent 4 }}
spec:
  # Переменная для масштабирования
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "whoami.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "whoami.selectorLabels" . | nindent 8 }}
    spec:
      # --- ДОБАВЛЕННЫЙ БЛОК ДЛЯ СЕКРЕТОВ ---
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # -------------------------------------
      containers:
        - name: {{ .Chart.Name }}
          # Собираем строку образа из репозитория и тега
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP