apiVersion: v1
kind: Service
metadata:
  name: {{ include "whoami.fullname" . }}
  labels:
    {{- include "whoami.labels" . | nindent 4 }}
spec:
  # Берем тип сервиса из values.yaml
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "whoami.selectorLabels" . | nindent 4 }}