# Количество копий приложения
replicaCount: 4

image:
  repository: registry.gitlab.com/0001k-group/0001k-project
  # Если оставить пустым, возьмет версию из Chart.yaml (AppVersion)
  tag: "884a1d33"

service:
  type: NodePort
  port: 80

imagePullSecrets:
  - name: gitlab-registry