# Количество копий приложения
replicaCount: 4

image:
  repository: traefik/whoami
  # Если оставить пустым, возьмет версию из Chart.yaml (AppVersion)
  tag: "latest"

service:
  type: NodePort
  port: 80